### ISSUE TITLE
xpos and upos meaning 

### ISSUE THREAD

**Issue by athammad** [UniversalDependencies/UD_Italian#1]
Hi,

I would like to know where I can find the correspondent meaning of each acrimonious/tagset for the `upos `and `xpos` fields .

thank you

**Comment by jnivre** [comment]
Documentation of the UPOS tags is included in the UD guidelines (under pos tags):
https://universaldependencies.org/guidelines.html

The XPOS tags are language-specific and not defined by the UD standard, so you need to consult the documentation for each treebank (or contact the treebank provided).
